CREATE DATABASE FORTES_PROJETO;
USE FORTES_PROJETO;

CREATE TABLE IF NOT EXISTS USUARIOS(
LOGIN INT PRIMARY KEY,
NOME VARCHAR(45),
EMAIL VARCHAR(45) NOT NULL,
SENHA VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTITUICOES(
CNPJ INT PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
CIDADE VARCHAR(45) NOT NULL,
BAIRRO VARCHAR(45) NOT NULL,
NUMERO INT NOT NULL,

USER_LOGIN INT NOT NULL,
CONSTRAINT USER_INST FOREIGN KEY(USER_LOGIN) REFERENCES USUARIOS(LOGIN) /* PRIMARY KEY */
);

CREATE TABLE IF NOT EXISTS FORMULARIOS(
ID_FORMULARIOS INT PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
CEP INT NOT NULL,
UF VARCHAR(5) NOT NULL,
CIDADE VARCHAR(45) NOT NULL,
BAIRRO VARCHAR(45) NOT NULL,
TELEFONE INT NOT NULL,
DATA_INICIO_PROJETO DATE,
DATA_TERMINO_PROJETO DATE,
IMAGEM BLOB,

INST_CNPJ INT NOT NULL,
CONSTRAINT INST_FORM FOREIGN KEY(INST_CNPJ) REFERENCES INSTITUICOES(CNPJ) /* PRIMARY KEY */
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
ID_FUNCIONARIOS INT PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
IDADE INT,
CIDADE VARCHAR(45) NOT NULL,
BAIRRO VARCHAR(45) NOT NULL,
NUMERO INT NOT NULL,

USER_LOGIN INT NOT NULL,
CONSTRAINT USER_FUNC FOREIGN KEY(USER_LOGIN) REFERENCES USUARIOS(LOGIN), /* PRIMARY KEY */
FORM_ID INT NOT NULL,
CONSTRAINT FORM_FUNC FOREIGN KEY(FORM_ID) REFERENCES FORMULARIOS(ID_FORMULARIOS),
INST_CNPJ INT NOT NULL,
CONSTRAINT INST_FUNC FOREIGN KEY(INST_CNPJ) REFERENCES INSTITUICOES(CNPJ) /* REFERENCIA DE FORM P INST */
);

CREATE TABLE IF NOT EXISTS PROJETOS(
ID_PROJETOS INT PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
RESPONSAVEL VARCHAR(45) NOT NULL,
TIPO_PROJETO VARCHAR(75) NOT NULL,
ACOES_PRATICADAS TEXT,
REGIOES_ALCANCE TEXT,
INFRAESTRUTURA VARCHAR(45) NOT NULL,

FUNC_ID INT NOT NULL,
CONSTRAINT PROJ_FUNC FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS(ID_FUNCIONARIOS),
USER_LOGIN INT NOT NULL,
CONSTRAINT USER_PROJ FOREIGN KEY(USER_LOGIN) REFERENCES USUARIOS(LOGIN) /* REFERENCIA DE FUNC P USER */
);

/* CONTINUAR DAQUI !!! */

CREATE TABLE IF NOT EXISTS FORMULARIOS_HAS_PROJETOS(
FUNC_ID INT NOT NULL,
CONSTRAINT PROJ_FUNC FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS(ID_FUNCIONARIOS),
USER_LOGIN INT NOT NULL,
CONSTRAINT USER_PROJ FOREIGN KEY(USER_LOGIN) REFERENCES USUARIOS(LOGIN) /* REFERENCIA DE FUNC P USER */
);